### ISSUE TITLE
$populate enhancement

### ISSUE THREAD

**Issue by evgenyboxer** [feathersjs-ecosystem/feathers-mongoose#149]
Hey,

I really like using $populate (sometimes, I prefer that over the populate hook).
One downside I found is that I couldn't pass multiple populate statements.

Here's how you could query:

```
query: {
  $populate: {
    children: [
      { path: 'colA', populate: { path: 'fieldA' } },
      { path: 'colB', populate: { path: 'fieldB' } },
    ],
  },
},
```

and the service could look like:

```
// Handle $populate
if (filters.$populate) {
  if (filters.$populate.children) {
    filters.$populate.children.forEach((populate) => q.populate(populate));
  } else {
    q.populate(filters.$populate);
  }
}
```

Thoughts on this?

**Comment by marshallswain** [comment]
@evgenyboxer why not use an array directly?

```js
query: {
  $populate: [
    { path: 'colA', populate: { path: 'fieldA' } },
    { path: 'colB', populate: { path: 'fieldB' } },
  ]
},
```

and

```js
// Handle $populate
if (filters.$populate) {
  if (Array.isArray(filters.$populate) {
    filters.$populate.forEach((populate) => q.populate(populate));
  } else {
    q.populate(filters.$populate);
  }
}
```

Would that work?

**Comment by olaferlandsen** [comment]
> @evgenyboxer Good idea! Why not use an array directly?
> 
> ```js
> query: {
>   $populate: [
>     { path: 'colA', populate: { path: 'fieldA' } },
>     { path: 'colB', populate: { path: 'fieldB' } },
>   ]
> },
> ```
> 
> and
> 
> ```js
> // Handle $populate
> if (filters.$populate) {
>   if (Array.isArray(filters.$populate)) {
>     filters.$populate.forEach((populate) => q.populate(populate));
>   } else {
>     q.populate(filters.$populate);
>   }
> }
> ```
> 
> Would that work?

Can you give me a full example of this?
I need allow sub-populate like:
```javascript
{
    $populate: [
        {
            path: "author",
            populate: [{path: "image"}]
        }
    ]
}
```
