### ISSUE TITLE
Virtuals Lean and Populate and toObject

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-mongoose#198]
I'm not sure if what I want is just not possible or something is wrong. I basically want to be able to populate and use virtual fields.

Populate only works when lean is set to true which then means victuals don't work.

Changing lean to false allows the virtual to work but I then have to use `toObject` to get populate to work and this makes virtuals not work again. So this is my after hooks

```
exports.after = {
  all: [
    service.hooks.toObject({}),
    populate({
      schema: schema
    })
  ]
``` 
and I have set these on the model

```
schema.set("toJSON", { virtuals: true });
schema.set("toObject", { virtuals: true });
```

**Comment by marshallswain** [comment]
Didn't that work?

**Comment by eddyystop** [comment]
You may want to use Mongo's or Sequelize's inherent populate features instead of the `populate` hook. Sequelize's would be much more performant.

Otherwise you have to work about the issue, which is possible.

**Comment by dottodot** [comment]
@marshallswain no that didn't work, if I remove the `toObject` and `populate` my virtuals work but with them in place virtuals don't work.

**Comment by marshallswain** [comment]
I see. You'll probably have to check out the Mongoose docs and use their populate feature, then, as @eddyystop suggested.
