### ISSUE TITLE
$populate security risk

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs-ecosystem/feathers-mongoose#207]
### Steps to reproduce

Following scenario:
I got two services : "comments" and "users".
Users is the private service which holds the user data and can only be accessed if authorized.
Comments is a public endpoint and serves datasets containing a ObjectRef to the user that created the comment.
Now i do a "comments?$populate[]=user"

### Expected behavior
It should not give me the complete user dataset without being authorized as this user

### Actual behavior
It does give me everything. How can i get it secure?

### System configuration

    "feathers-mongoose": "^5.1.0",

**Comment by longseespace** [comment]
You can always write a hook to prevent this however I agree that `$populate` _should be_ disabled by default.

**Comment by daffl** [comment]
Agreed. I've been debating of disabling anything that is not covered by the official query syntax by default and having to explicitly whitelist the functionality you want.

We're planning major releases for the database adapters for https://github.com/feathersjs/feathers/issues/608 so that might be a good time to do that.

**Comment by ekryski** [comment]
imho `$populate` should be a valid query param but it should trigger `populate` hooks that have been registered on the service. That way it's a bit more explicit what you are exposing.

Using the internal mongoose `$populate` is nice for convenience but is kind of hack legacy solution from before @eddyystop did so much awesome work on the common hooks.

**Comment by crobinson42** [comment]
I agree with @ekryski. I don't think disabling a query param is the best solution. However, creating a before/after populate callback per service sounds flexible and reasonable enough to address the security concerns.

**Comment by ellipticaldoor** [comment]
There is a hook that disables populate for the moment?

**Comment by daffl** [comment]
```js
function(hook) {
  delete hook.params.query.$populate;
}
```

?

**Comment by ellipticaldoor** [comment]
it works, I added that in the find and get before in the app.hooks.js

**Comment by ellipticaldoor** [comment]
I you still want that functionality in the backend you can use this hook

``` javascript
// Disables mongoose $populate in the front
const { when } = require('feathers-hooks-common')

module.exports = () => {
	return when(
		hook => hook.params.provider,
		hook => {
			delete hook.params.query.$populate
			return hook
		}
	)
}
```

**Comment by davidchalifoux** [comment]
@daffl Just ran in to this problem. I want to use the populate feature, however using the `discard()`hook is not working to remove data such as passwords. What is your suggest workaround to process the data?

**Comment by daffl** [comment]
What I said in my previous comment. Just `delete` those properties manually in an `after` hook or use something like [Lodash _.omit](https://lodash.com/docs/4.17.4#omit).
