### ISSUE TITLE
Passing through collation options for case insensitive sorting

### ISSUE THREAD

**Issue by cfitton** [feathersjs-ecosystem/feathers-mongoose#211]
### Steps to reproduce
Create a service, then attempt to sort case insensitively on one of the document fields

### Expected behavior
Should be able to pass through collation options to be able to set the `strength` of the sort.

### Actual behavior
No mechanism for passing through collation options

### Suggested Fix
Addition of `$collation` or `$options` query param to allow passing through of collation options, similar to how `$sort` is passed through

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 5.1.0

**NodeJS version**: 8.4.0

**Operating System**: Ubuntu 16.04

**Browser Version**: Chrome 60

**React Native Version**: N/A

**Module Loader**: N/A

**Comment by daffl** [comment]
Could you provide an example how to normally pass collations into Mongoose?

**Comment by cfitton** [comment]
There's two options to provide collation:
```javascript
const collation = { locale: 'en', strength: 2 }
MyModel.find({}, null, { collation: collation });
```
or
```javascript
const collation = { locale: 'en', strength: 2 }
const query = MyModel.find({})
query.collation(collation)
```

**Comment by Creiger** [comment]
I think the second approach is very similar to MongoDB which is already implemented in feathers-mongodb.

**Comment by superbarne** [comment]
any updates on this issue?

**Comment by superbarne** [comment]
#263

**Comment by superbarne** [comment]
@daffl this can be closed
