### ISSUE TITLE
poulate after create hook

### ISSUE THREAD

**Issue by travisstaloch** [feathersjs-ecosystem/feathers-mongoose#213]
### Expected behavior
I have a model called tables with a ref to tablesB which has a ref to tablesA.  When I create a new tables document, I want feathers to return an object populated with data from tablesB and tablesA.  I've shown some of the things I've tried in comments of the code below including using mongoose-autopopulate, mongoose model.pre()/post() 'save' / 'init' / 'find' / 'findOne' middleware, and several different feathers after create hooks.  

### Actual behavior
After create, the record only has _id of tablesB with no further data from the referenced tablesB document.  These all work with find and delete operations, just not create.  

tables.model.js
```javascript
  const tables = new Schema({
    name: { type: String, required: true },
    tablesB: {
      type: Schema.Types.ObjectId,
      ref: 'tablesB',
      autopopulate: true
    },
  })

  // tables.plugin(autopopulate)

  // var autoPopulateTTB = function(next) {
  //   this.populate('tablesB')
  //   next()
  // }

  // tables.pre('findOne', autoPopulateTTB)
  //   .pre('find', autoPopulateTTB)
  //   .pre('save', autoPopulateTTB)
  // tables.post('save', function(doc, next) {
  //   autoPopulateTTB() 
  // })
```
tables.hooks.js
```javascript
  return function populateTables (hook) {
    hook.params.query.$populate = Object.assign(hook.params.query.$populate || {}, {
      path: 'tableB',
      populate: { path: 'tablesA' }
    })
    return Promise.resolve(hook)
  }
```

package.json
```javascript
    "feathers": "^2.2.0",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-authentication-oauth2": "^0.2.6",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.7.3",
    "feathers-mongodb": "^2.9.0",
    "feathers-mongoose": "^3.6.2",
    "feathers-rest": "^1.8.0",
    "feathers-socketio": "^2.0.0",
```
**NodeJS version**: v6.11.1
**Operating System**: Win 10

I've tried a number of solutions beyond what is listed here and spent quite a while searching for a solution.  Any help is greatly appreciated.  Thank you.

**Comment by Mattchewone** [comment]
@travisstaloch Have you tried just using an after hook to populate, rather than using the mongoose $populate methods?

```js
  const tables = new Schema({
    name: { type: String, required: true },
    tablesB: {
      type: Schema.Types.ObjectId,
      ref: 'tablesB'
    },
  })
```

hook file:
```js
const { shallowPopulate } = require('feathers-shallow-populate')
 
const options = {
  include: {
    service: 'tablesB',
    nameAs: 'tablesB',
    keyHere: 'tablesB',
    keyThere: '_id'
  }
}
 
return {
  after: {
    all: shallowPopulate(options)
  }
}
```

**Comment by pranjuls** [comment]
Could you please explain why to use populate in after hook instead of a before hook?
