### ISSUE TITLE
Feathers error 409 - conflict: message 'follows: null already exists''

### ISSUE THREAD

**Issue by ducnvhn** [feathersjs-ecosystem/feathers-mongoose#219]
I'm facing very strange problem. 

when I run 'create' from my client on a service, Always return error with a message 'follows: null already exists'
my service is very simple 
```
import mongooseService from 'feathers-mongoose';
import PostModel from './postmodel';
export default function postService() {
 const app = this;
 app.service('/post', mongooseService({Model: PostModel}));
// apply no hooks
}
// the model 
import mongoose from 'mongoose';
const Schema= mongoose.Schema;
const PostSchema = new Schema({
 title: { type: String},
content: { type: String} 
// that's all 
});
const PostModel = mongoose.model('Post', PostSchema);
export default PostModel;
```
Please help if you have a solution. 

Thanks in advance.

**Comment by daffl** [comment]
That seems kind of odd, I don't think I've ever seen that. Do you have a `unique` constraint somewhere else (e.g. creating a user?)

**Comment by ducnvhn** [comment]
many thanks for your advise. 
I have an array of user who follow the post and was defined in the schema like this
````
// post shema
follows:[{type: Schema.Types.ObjectId, unique: true, ref:'User'}]
````
and then my mongodb create an index on this field. if I obmit this field in creat method service will throw this err. 
question: how to make the array of unique ref to User. 

thanks.

**Comment by daffl** [comment]
If you want to allow unique indices to also be null in MongoDB you have to set `sparse: true`:

```
// post shema
follows:[{ type: Schema.Types.ObjectId, unique: true, ref:'User', sparse: true }]
```

**Comment by ducnvhn** [comment]
thank you so much @daffl . will try it.

**Comment by ducnvhn** [comment]
hi @daffl . 
I have try to change my Schema 
````
follows: [{ type: Schema.Types.ObjectId, ref: 'user', unique: true, sparse: true}]
````
and when I create a new post, there are still errors : 
````
Conflict: follows: undefined already exists
...
code: 409
````
is there any other thing I have to change in the Schema/Model/Service ?

**Comment by daffl** [comment]
I'm not sure if this works for arrays but it might also be

```
follows: [{
  type: Schema.Types.ObjectId,
  ref: 'user',
  index: { unique: true, sparse: true }
}]
```

**Comment by ducnvhn** [comment]
not work in my case. Whenever I update the first ref user into this array, Mongo create an index on this field. Think that's my problem with Mongo other than this. Thanks @daffl l.

**Comment by hcbh96** [comment]
@daffl I've been slightly spamming slack and I really apologise for that. 

This issue I am getting is kind of similar to the one here.

I am currently able to create one MongoDB user, along with an _id of type ObjectId,

I am able to authenticate my user, and use that authentication to fetch the list of users, this is a user object. 

`{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "_id": "5a9a8c3e4b0aac22847635fe",
            "updatedAt": "2018-03-03T11:51:26.171Z",
            "createdAt": "2018-03-03T11:51:26.171Z",
            "email": "test@test.com",
            "__v": 0
        }
    ]
}`

What i am not able to do is create a new user as each time I try I get an error code of 409 with the following response

`{
    "name": "Conflict",
    "message": "id: null already exists.",
    "code": 409,
    "className": "conflict",
    "errors": {
        "id": null
    }
}`

I am really sorry for sending so many messages on this, I just really want and need to get my head around what is going on. Thank you very much for providing any insight

**Comment by HurmisIndia** [comment]
> @daffl I've been slightly spamming slack and I really apologise for that.
> 
> This issue I am getting is kind of similar to the one here.
> 
> I am currently able to create one MongoDB user, along with an _id of type ObjectId,
> 
> I am able to authenticate my user, and use that authentication to fetch the list of users, this is a user object.
> 
> `{ "total": 1, "limit": 10, "skip": 0, "data": [ { "_id": "5a9a8c3e4b0aac22847635fe", "updatedAt": "2018-03-03T11:51:26.171Z", "createdAt": "2018-03-03T11:51:26.171Z", "email": "test@test.com", "__v": 0 } ] }`
> 
> What i am not able to do is create a new user as each time I try I get an error code of 409 with the following response
> 
> `{ "name": "Conflict", "message": "id: null already exists.", "code": 409, "className": "conflict", "errors": { "id": null } }`
> 
> I am really sorry for sending so many messages on this, I just really want and need to get my head around what is going on. Thank you very much for providing any insight

I just faced the same problem with one of my collections. First single doc was written correctly but no more new additions were failing with mentioned conflict error.
I must mention the schema 
```
{
 fieldOne : String,
 fieldTwo: [String]
}
```
-- that's it!
But any patch or get requests were executing successfully on first record.

My codes are running on localhost and DB on mongo atlas cloud. 

After wasting all the energy finally deleted the entire collection. 

NOW IT"S WORKING AS DESIRED!

Thank god it was in development phase!
