### ISSUE TITLE
Are nested schemas saved?

### ISSUE THREAD

**Issue by MaxiSantos** [feathersjs-ecosystem/feathers-mongoose#220]
Hello, I'm following the doc for mongoose [http://mongoosejs.com/docs/subdocs.html](http://mongoosejs.com/docs/subdocs.html) and it looks after the save method is called on the parent schema then the child schema is saved. But it looks all the save functionality is done in feathers-mongoose ? My nested schemas are not saved.

I'm using postman to test the api.

If there is other place where to ask this specific question for feathersjs just put it on the readme please.

**Module versions** (especially the part that's not working):
"mongoose": "^4.9.5",
mongodb: v3.4.9

**NodeJS version**: 6.11.0

**Operating System**: Ubuntu 14.04

**Comment by jamesjnadeau** [comment]
Hi @MaxiSantos,

Can you provide the code you are using? 
Does this work removing feathers-mongoose from the equation?

**Comment by MaxiSantos** [comment]
I'm using this boilerplate for redux-featherjs [https://github.com/brandiqa/redux-crud-example](https://github.com/brandiqa/redux-crud-example) There is only one model. I started to work based on this boilerplate and now I'm seeing some issues with nested schemas.

This is schema A and there it has a nested schema (seed)

After I do a POST I see the schema A is saved with the seed. But the seed is not saved in its own collection. According to the docs [http://mongoosejs.com/docs/subdocs.html](http://mongoosejs.com/docs/subdocs.html) I was expecting to see the seed schema saved in its own collection.

`
module.exports = function (app) {
  const schema = {
    seed : [new mongooseClient.Schema(seedSchema())],
    action : {
      type: String,
      required: [true, 'Phone is required'],
    }
  };
  return schema;
};
`

**Comment by MaxiSantos** [comment]
My bad.. I'm using embedded schemas expecting to save schemas in their own collections which is wrong. I have to save the ref 
[https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/)
[http://mongoosejs.com/docs/populate.html](http://mongoosejs.com/docs/populate.html)
