### ISSUE TITLE
Add example for nested schemas using feathers

### ISSUE THREAD

**Issue by MaxiSantos** [feathersjs-ecosystem/feathers-mongoose#221]
For nested schemas where you want to persist them in separate collections ( [https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/) ) it would be nice to have an example of how to integrate the mongoose way with feathers.js ( [section saving-ref](http://mongoosejs.com/docs/populate.html) )

After a couple of hours I'm still not able to save my nested schema into a separate collection (I'm not sure exactly where to add the example of the saving ref from mongoose url

**Comment by daffl** [comment]
If you have two separate services you might want to look into doing exactly what the Mongoose "Saving refs" documentation suggests and make to service calls.

```js
app.service('authors').create({
  name: 'Ian Fleming',
  age: 50
}).then(author => {
  return app.service('stories').create({
    title: 'Casino Royale',
    author: author._id    // assign the _id from the person
  });
})
```

**Comment by MaxiSantos** [comment]
Thank you, but where do I get the dynamic data? 

I'm using this boilerplate and I liked that with just the configuration of the database I started to use the REST api for the contacts.. [https://github.com/brandiqa/redux-crud-example](https://github.com/brandiqa/redux-crud-example) But now I'm a little lost on where to get access to the data that arrives to the server. If you can guide me a little or at least tell me what topic to read on feather (I've looked at services [https://docs.feathersjs.com/api/services.html](https://docs.feathersjs.com/api/services.html) and database common [(https://docs.feathersjs.com/api/databases/common.html)](uhttps://docs.feathersjs.com/api/databases/common.htmlrl)

Maybe it's something really simple and when I see it I'll say: hooo, that is... 😄

**Comment by daffl** [comment]
If you really want to submit nested data, this is would also work analogous to the Mongoose example by pre-creating an object id and using that to create the nested entries (plus making sure that those data does not get added to the original service call) in a `before` `create` hook:

```js
const lodash = require('lodash');

app.service('authors').hooks({
  before: {
    async create(hook) {
      const _id = new mongoose.Types.ObjectId();
      const { stories } = hook.data;
      
      hook.data._id = _id;

      for(let story of stories) {
        const storyData = Object.assign({
          authorId: _id
        }, story);

        await hook.app.service('stories').create(story);
      }

      return hook;
    }
  }
});
```

**Comment by MaxiSantos** [comment]
Hooo, I see, thank you very much.

**Comment by MaxiSantos** [comment]
It worked ! I'm starting to getting love with feathers.
