### ISSUE TITLE
Patch/update should load the document and then save to call defaults/setters

### ISSUE THREAD

**Issue by ricardovf** [feathersjs-ecosystem/feathers-mongoose#231]
When i call the patch endpoint, the setters on the the moongoose schema is not called.

http://mongoosejs.com/docs/3.4.x/docs/api.html#model_Model-findByIdAndUpdate

``````
Although values are cast to their appropriate types when using the findAndModify helpers, the following are not applied:

defaults
setters
validators
middleware

If you need those features, use the traditional approach of first retrieving the document.
``````

i know i can do it on the feathers service layer, with a pre-hook, but i think the model setters should be respected.

**Comment by daffl** [comment]
This should be possible by setting the `lean` option of this adapter to to `false` (default is `true`).
