### ISSUE TITLE
Converting to an object in mongoose

### ISSUE THREAD

**Issue by axmad22** [feathersjs-ecosystem/feathers-mongoose#235]
The mongoose adapter uses **toObject**  while the authentication-local uses **toJSON**,  why not keep it consistent since both functions do the same thing. I am only saying this cause I have modified my schemes **toObject** like so 

```
if (!userSchema.options.toObject) userSchema.options.toObject = {};
        userSchema.options.toObject.transform = function (doc, ret) {
            ret.id = ret._id;
            delete ret._id;
            delete ret.__v;
            return ret;
        };
} 
``` 
and its calling the **toJson**, Am still learning **Feathers** is changing the _id a bad idea. 

Nice framework by the way,  best one yet

**Comment by daffl** [comment]
`toJSON` is a standard used by [JSON.stringify](standard) so it is probably the one that should be used.
