### ISSUE TITLE
DeprecationWarning: collection.count is deprecated, and will be removed in a future version

### ISSUE THREAD

**Issue by axmad22** [feathersjs-ecosystem/feathers-mongoose#246]
Hate to be the bearer of bad news, but as of "mongoose": "^5.2.1",  feathers-mongoose
pops a warning that it has deprecated the count() method and will it be replaced with countDocuments, estimatedDocumentCount instead

**Comment by daffl** [comment]
A pull request changing the method call in https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/lib/service.js#L101 accordingly would be great news 😄

**Comment by edenmw** [comment]
My approach
\node_modules\mquery\lib\collection\node.js:50
NodeCollection.prototype.count = function(match, options, cb) {
  this.collection.count(match, options, cb);
};
=> NodeCollection.prototype.countDocuments = function(match, options, cb) {
  this.collection.countDocuments(match, options, cb);
};

\node_modules\mongoose\lib\query.js:1950
this._collection.count(conds, options, utils.tick(callback));
=> this._collection.countDocuments(conds, options, utils.tick(callback));

**Comment by daffl** [comment]
Closed via #250
