### ISSUE TITLE
There is total but no data

### ISSUE THREAD

**Issue by f4th4n** [feathersjs-ecosystem/feathers-mongoose#254]
I have a 5 docs in collections. When I make request it will always return total 5 even if the request is already filtered, e.g /posts?name=something.

```
{
    "total": 5,
    "limit": 10,
    "skip": 0,
    "data": []
}
```

Working on feathers-mongoose version <= 6.1.2 but not working on version 6.1.3.

Environment:
Debian Jessie
Node 10
@feathersjs/feathers@3.1.7
feathers-mongoose@6.1.3
mongoose@5.2.7

**Comment by daffl** [comment]
This has been fixed in version 6.1.4
