### ISSUE TITLE
[question][Documents] RunValidators is set by default?

### ISSUE THREAD

**Issue by dungla4** [feathersjs-ecosystem/feathers-mongoose#255]
Hello, this is not an issue, just a question about README. Seem that I don't understand it correctly. Could some guys can explain it, please?
In README, there's an [paragraph](https://github.com/feathersjs-ecosystem/feathers-mongoose#paramsmongoose):
## params.mongoose
When making a service method call, params can contain a mongoose property which allows you to modify the options used to run the Mongoose query. Normally, this will be set in a before hook:
```
app.service('messages').hooks({
  before: {
    patch(context) {
      // Set some additional Mongoose options
      // The adapter tries to use sane defaults
      // but they can always be changed here
      context.params.mongoose = {
        runValidators: true,
        setDefaultsOnInsert: true
      }
    }
  }
});
```
And here is my concern. With this docs, does it mean `runValidators` is set to true by default?

**Comment by jamesjnadeau** [comment]
`runValidators` is set to true by default. It was set here:
https://github.com/feathersjs-ecosystem/feathers-mongoose/pull/87/files#diff-480db08609ef6a51bf20f049cc9bda48R143

and you can view the defaults used in the update operation here:
https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/5d956bc52eea93b57cb9d57bf2cbecd1fb6f4f1f/lib/service.js#L202

and here it is in patch:
https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/5d956bc52eea93b57cb9d57bf2cbecd1fb6f4f1f/lib/service.js#L252

Hope this helps!

**Comment by dungla4** [comment]
@jamesjnadeau Thank you very much. In source code, it 's set by default, I just concern about documents.
When I read the documents, I think it's not set by default. This option is disable from [mongoose](`runValidators` is off by default from [mongoose](http://mongoosejs.com/docs/validation.html#update-validators), so I'm very surprise while seeing this option in query.
Do you think documents should mention `runValidators: true` is default for `update/patch`? It helps someone has bad English like me to understand clearly

**Comment by jamesjnadeau** [comment]
Maybe? From my understanding the current functionality works like other feathers adapter. I personally think having runValidators set to true is a good choice.

Feel free to submit a pull request with the updated docs.

**Comment by dungla4** [comment]
@jamesjnadeau I submit [this PR](https://github.com/feathersjs-ecosystem/feathers-mongoose/pull/256).
Thanks for helping!
