### ISSUE TITLE
Conflict error for compound indexes is not correct

### ISSUE THREAD

**Issue by cdimitroulas** [feathersjs-ecosystem/feathers-mongoose#258]
### Steps to reproduce

1. Create a compound index for your collection:
```js
const mongoose = require('mongoose')

const schema = new mongoose.Schema({
  // random fields used as an example
  firstId: { type: mongoose.Types.ObjectId },
  secondId: { type: mongoose.Types.ObjectId }
})

schema.index({ firstId: 1, secondId: 1 }, { unique: true })
```
2. Create two documents, both with the same `firstId` and `secondId` field values and inspect the error message returned from mongoose. It will look something like this:
`firstId: ObjectId(\'5b891cf30d74a9432c0ee036\'), : ObjectId(\'587775b068194a6b3c818dce\') already exists.`

### Expected behavior
Feathers mongoose should handle a 1100 or 11001 MongoDB error and display a useful error message for the user of the library

### Actual behavior
This works fine for regular indexes, but when there is a compound index the error message is rather
obscure.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
`feathers-mongoose`: 6.1.2
`mongoose`: 4.13.14

**NodeJS version**: 8.11.2

**Operating System**: Ubuntu 16.04

**Comment by daffl** [comment]
`firstId: ObjectId(\'5b891cf30d74a9432c0ee036\'), : ObjectId(\'587775b068194a6b3c818dce\') already exists.` as an error message is not really incorrect is it?

Since everybody has a different idea what "useful" means, most adapters don't customize database error messages. The best way to customize errors to your needs is by using [Feathers error hooks](https://docs.feathersjs.com/api/hooks.html).

**Comment by cdimitroulas** [comment]
It is incorrect, it should say `firstId: ObjectId("..."), secondId: ObjectId("...")`. The key before the second ObjectId is blank

**Comment by cdimitroulas** [comment]
Reminder to self to have a stab at a PR for this. Unless @daffl you really believe this is not an issue and the error message is correct (in which case, could you explain to me how I'm misreading it?)

**Comment by daffl** [comment]
No, that's fair. Is that a problem in the conflict error handler part (https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/lib/error-handler.js#L4)?

**Comment by cdimitroulas** [comment]
Yes, I believe there's something wrong or incomplete with the regex there.

**Comment by daffl** [comment]
Might make sense to make the Regex only apply to the simple case that it actually covers then. Parsing the error message probably wasn't a good idea to begin with (strangely it is what Mongoose appears to recommend in the issues related to that) but I don't want to make another breaking change for something that might make things less user friendly.

**Comment by cdimitroulas** [comment]
@daffl ^ what do you think of my proposed idea?

**Comment by daffl** [comment]
We probably could do the same thing the new Sequelize adapter is doing and add a hidden property with the original error (https://github.com/feathersjs-ecosystem/feathers-sequelize#migrating).

**Comment by daffl** [comment]
It basically just adds the original error in a Symbol error property (see https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/utils.js) so it can be accessed and used in the server-side error handler.
