### ISSUE TITLE
Error: You must provide a Mongoose Model (at new Service) on Model variable name change

### ISSUE THREAD

**Issue by michaelcerne** [feathersjs-ecosystem/feathers-mongoose#265]
### Steps to reproduce

1. Follow the example located [here](https://github.com/feathersjs-ecosystem/feathers-mongoose#example)
2. Change the name of the variable `Model` to anything else
3. The error: `Error: You must provide a Mongoose Model (at new Service)` is thrown

### System configuration

Linux Mint 18.3, running Node 8.12.0

package.json dependencies:
`"dependencies": {
    "@feathersjs/errors": "^3.3.4",
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3",
    "feathers-mongoose": "^6.1.4",
    "mongoose": "^5.2.17"
  }`

NOTE: I've isolated the issue down to just the name of the variable, it works flawlessly when named `Model`, but when changed fails. The only references in the main file are the import (require) and the service itself.

Let me know what other info is needed, thanks.

**Comment by daffl** [comment]
That's because `Model` is the name of the option. If you want to change the variable name it still has to be passed as `Model` as the service initialization options.

```
app.use('/messages', service({
  Model: myOtherModelName
}));
```

**Comment by michaelcerne** [comment]
@daffl That did it. Thanks!

**Comment by daffl** [comment]
Side note: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment gives a good overview of destructuring in ES6 (which is what was happening here).
