### ISSUE TITLE
Schema validation does not run for patch requests

### ISSUE THREAD

**Issue by jonnyparris** [feathersjs-ecosystem/feathers-mongoose#266]
### Steps to reproduce

I have a schema like this:
``` javascript
const approverDetailsRequired = foo => {
  const { state: currentState } = foo
  const { SUBMITTED, APPROVED, PAID, REJECTED } = FooStates
  const approvalNeededForStates = [SUBMITTED, APPROVED, PAID, REJECTED]
  return approvalNeededForStates.includes(currentState)
}

const fooSchema = new Schema(
  {
    state: {
      type: String,
      enum: [DRAFT, SUBMITTED, APPROVED, REJECTED],
      default: DRAFT,
      required: true
    },
    approver: {
      name: {
        type: String,
        trim: true,
        required: [
          approverDetailsRequired,
          'Approver name is required to submit, approve, reject or process a timesheet'
        ]
      },
    }
  })
```

Then I run a patch request that only includes ` state: { APPROVED } ` in the body.

### Expected behavior
I should get a BadRequest error response; probably something like:
``` json
{
  "name": "BadRequest",
  "message": "foo validation failed: weekStarting: Path `approver.name` is required.",
  "code": 400,
  "className": "bad-request",
  "errors": {
    "approver.name": {
      "message": "Path `approver.name` is required.",
      "name": "ValidatorError",
      "properties": {
        "message": "Path `approver.name` is required.",
        "type": "required",
        "path": "approver.name"
      },
      "kind": "required",
      "path": "approver.name",
      "$isValidatorError": true
    }
  }
}

```

### Actual behavior
It happily updates the state to approved despite the document not having approver details.
What am I doing wrong?

### System configuration
**Module versions**
feathers-mongoose: 6.1.4
mongoose: 5.3.1
mongo: 3.6

**NodeJS version**:
9.8.0

**Comment by daffl** [comment]
You can set `runValidators` [as documented in params.mongoose](https://github.com/feathersjs-ecosystem/feathers-mongoose#paramsmongoose).

**Comment by jonnyparris** [comment]
I thought runValidators was set to true by default? I have also tried setting the params manually though

**Comment by jonnyparris** [comment]
PEBCAK 😅

**Comment by FaizuddinEverest** [comment]
The `runValidators` is set to `true` by default as seen in the source code here:
https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/lib/service.js#L244

But the `patch` calls are still not running validations for me. @jonnyparris did you take any extra steps to make sure the document is validated?

**Comment by jonnyparris** [comment]
@FaizuddinEverest Sorry I don't have the project available anymore to comb through how I resolved this one. I think it must have been something silly and unrelated on my part otherwise I _like_ to think I would have shared a more helpful closing comment 😬
Good luck!
