### ISSUE TITLE
feathers update service cleans document

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs-ecosystem/feathers-mongoose#274]
I have a problem because something is wrong with my service update. I have correctly created model. For example, when I use below service:

`app.service('teachers').update(_id, { $set: { "name": "firstName" }});`

my document is cleaned instead update. There is only one field left:

`{"_id":ObjectId("...")}`

What is wrong?

**Comment by SeaDog505** [comment]
> I have a problem because something is wrong with my service update. I have correctly created model. For example, when I use below service:
> 
> `app.service('teachers').update(_id, { $set: { "name": "firstName" }});`
> 
> my document is cleaned instead update. There is only one field left:
> 
> `{"_id":ObjectId("...")}`
> 
> What is wrong?

**Comment by daffl** [comment]
Have you tried `patch`? Update is supposed to replace the entire document (and it looks like the `$set` didn't get picked up).

**Comment by SeaDog505** [comment]
I use patch method but I can't used it in this service because after using patch is running hook before and this way my app can work not correctly. For example, I have service which in there hook is running another service("teacher").patch().
I updated node, npm, feathers and more and now I have a problem with $set update. Previously I have not seen any problem with update.

**Comment by daffl** [comment]
In the latest version you can use `_patch` to call `patch` without hooks (see https://crow.docs.feathersjs.com/migrating.html#hook-less-service-methods).
