### ISSUE TITLE
Extra data directory included since version 7.0.0 

### ISSUE THREAD

**Issue by cesarmal** [feathersjs-ecosystem/feathers-mongoose#290]
When installing version 7.0.0 or greater, a directory called data is included in node_modules/feathers-mongoose. The installed package size becomes almost 1GB on version 7.0.0.
Version 6.3.0 does not contain this extra folder.

======= 7.0.0 ========
$ npm install --save feathers-mongoose@7.0.0
...
$ ls node_modules/feathers-mongoose
CHANGELOG.md  data  lib  LICENSE  mocha.opts  package.json  README.md
$ du -sh node_modules/feathers-mongoose/
906M	node_modules/feathers-mongoose/

======= 6.3.0 ========
$ npm install --save feathers-mongoose@6.3.0
...
$ ls node_modules/feathers-mongoose/
CHANGELOG.md  lib  LICENSE  mocha.opts  package.json  README.md
$ du -sh node_modules/feathers-mongoose/
96K	node_modules/feathers-mongoose/

If I am not mistaken, it must be a simple issue with the package building.

**Comment by daffl** [comment]
Oops, forgot that when you have a `.npmignore` npm will not use the folders from `.gitignore`. Should be fixed in the latest version.
