### ISSUE TITLE
gridfs support?

### ISSUE THREAD

**Issue by jnardone** [feathersjs-ecosystem/feathers-mongoose#315]
Is there native support in feathers-mongoose for gridfs?  I was hoping to leverage it as part of an uploads service (ideally avoiding feathers-blob and multer) but I don't see any mention in the docs.  What I'm not sure about is if it's necessary to be part of feathers-mongoose, or if it can be done side-by-side...

**Comment by daffl** [comment]
I don't believe there is anything this adapter can or needs to do. I'd probably use something like [mongoose-gridfs](https://www.npmjs.com/package/mongoose-gridfs).
