### ISSUE TITLE
$populate example in docs has a typo

### ISSUE THREAD

**Issue by xsl777** [feathersjs-ecosystem/feathers-mongoose#319]
const **service** = require('feathers-mongoose');

app.use('/posts', **mongoose**({
  Model,
  whitelist: [ '$populate' ]
});

should be 
const **mongoose** = require('feathers-mongoose')

**Comment by daffl** [comment]
Makes sense. You can submit a pull request by clicking the edit button at https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/README.md and making the change.
