### ISSUE TITLE
Populate 2 levels deep 

### ISSUE THREAD

**Issue by designalchemy** [feathersjs-ecosystem/feathers-mongoose#320]
Hello, wandering if this is possible ?

```
&$populate=attachments
&$populate=attachments.creator
```

creator is a ID REF inside the attachment table to a user

Currently its only populating attachments which is good, but also need to populate creator inside the attachments if possible,

Thanks !

Luke

**Comment by designalchemy** [comment]
IV tired this : `/items/?$populate[]=attachments.creator`
but this throws a invalid error

**Comment by designalchemy** [comment]
okay it works if i do : 
```
    '&$populate=attachments' +
    '&$populate[]=attachments.creator' +
```

**Comment by designalchemy** [comment]
@daffl  any idea how to do this please?

**Comment by designalchemy** [comment]
@ekryski you got any ideas ?

**Comment by daffl** [comment]
Use [params.mongoose](https://github.com/feathersjs-ecosystem/feathers-mongoose#paramsmongoose) and the [nested array populating syntax](https://stackoverflow.com/questions/19222520/populate-nested-array-in-mongoose).

**Comment by designalchemy** [comment]
@daffl  So this is not possible with the query string ? im going to have to create a custom hook to populate 2 levels ?

**Comment by daffl** [comment]
You could try the querystring representation of the query (`require('qs').stringify(nestedSyntax)`) but it may not work.

**Comment by designalchemy** [comment]
@daffl 
Not sure how id do that, but thanks for the responce i appreciate it

**Comment by daffl** [comment]
The code sample I showed should show how it looks:

```js
const qs = require('qs');
const query = qs.stringify({
  $populate: { 
     path: 'pages',
     populate: {
       path: 'components',
       model: 'Component'
     } 
  }
});

console.log(query);
```

This will print something like `$populate[path]=pages&$populate[populate][path]=components&$populate[populate][model]=Component` which would be the query string you'd pass. More information can be found in the [NodeJS querystring](https://nodejs.org/api/querystring.html) and [qs module](https://www.npmjs.com/package/qs) documentation.

**Comment by designalchemy** [comment]
Oh right i see ! 

Sorry i misunderstood, thanks a lot ill give it a test

**Comment by designalchemy** [comment]
@daffl 

`const attachAssets = () => async context => {
  const stringList = context.params.query['$populate'].join(' ')

  context.params.query['$populate'] = {
    path: `assets ${stringList}`,
    populate: {
      path: 'creator',
    },
  }

  return context
}`

😬

**Comment by johnnyx3m** [comment]
> The code sample I showed should show how it looks:
> 
> ```js
> const qs = require('qs');
> const query = qs.stringify({
>   $populate: { 
>      path: 'pages',
>      populate: {
>        path: 'components',
>        model: 'Component'
>      } 
>   }
> });
> 
> console.log(query);
> ```
> 
> This will print something like `$populate[path]=pages&$populate[populate][path]=components&$populate[populate][model]=Component` which would be the query string you'd pass. More information can be found in the [NodeJS querystring](https://nodejs.org/api/querystring.html) and [qs module](https://www.npmjs.com/package/qs) documentation.

Thanks @daffl This one works magically. Just a question, from this, can we also do a condition 2 levels down?

**Comment by DaddyWarbucks** [comment]
I am a bit confused here. The Feathers app should be using `qs` under the hood to parse queries already. This is typically handled with
```js
app.use(express.urlencoded({ extended: true }));
```

in app.js. So if you are using the proper "nested query syntax", then the query should be parsed correctly.


Try these solutions out. Mongoose should support a couple of different syntax for populate.

```js
// Mongoose supports space delimited string
&populate=attachments attachments.creator
// will become
q.populate('attachments attachments.creator')

// Mongoose supports array of strings
&populate[0]=attachments&populate[1]=attachments.creator
// will become
q.populate(['attachments', 'attachments.creator'])
```
