### ISSUE TITLE
patch is incorrectly applying the entire query when re-fetching

### ISSUE THREAD

**Issue by jnardone** [feathersjs-ecosystem/feathers-mongoose#321]
### Steps to reproduce

This issue happens when you issue a `.patch` request where the payload modifies fields that are in the query.  This is a regression from 6.x.

In 6.x, if you did 

```
const toUpdate = { foo: 'bar' };
const [item] = await service.patch(id, toUpdate, { query: { foo: { $ne: 'bar' } } });
```
(note: this fails in both single and multi cases, see explanation below)

### Expected behavior
you will get back the modified row(s) if the query filter (and ID) matched any records.

### Actual behavior
In 7.x, this no longer works.

This is because in service.js, this changed:

```
          const findParams = idList.length ? Object.assign({}, params, {
            query: {
              [this.id]: { $in: idList }
            }
          }) : params;
```

to

```
          query: Object.assign({
            [this.id]: { $in: idList }
          }, params.query)
```

which incorrectly applies the original query filters to the data that's being re-fetched.  This is wrong - patch should return me changed rows, and should not be applying my original filters (which will fail in this case, I just changed the data that I was searching for!)

# **BUT**

This does break uses of `$populate` which might also be part of the query.  We, of course, use both in different scenarios.  Ideally, the $populate portion would be pulled out and reapplied to the ensuing _getOrFind, but not the actual filters.

### System configuration

Tell us about the applicable parts of your setup.
Mongoose 7.3.2
Node 10.15.3

**Comment by arfanliaqat** [comment]
this is fixed in #362
