### ISSUE TITLE
How to pass collation from client?

### ISSUE THREAD

**Issue by jnardone** [feathersjs-ecosystem/feathers-mongoose#322]
### Steps to reproduce

Seeing the information here https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/211 I want to use collation from a query I send from feathers-client.

```
      const query = { $sort: { name: 1 } };
      const collation = { locale: 'en', strength: 1 };
      const { data } = await service.find({ query, collation }));
```

This code works server-side in testing.  But I need to be able to do this via the feathersjs client.

However, feathers-client ONLY passes the query (for security reasons).  So, the collation information is dropped.

Is there a reason "collation" is not another element in the query like `$sort` etc.?  How can I pass a custom collation from the client directly?

### Expected behavior

I specify a collation from the client and get information back from the service using that collation.

### Actual behavior

Collation is ignored

### System configuration

Feathers-mongoose 7.3.2
Node.JS 10.15.3
FeathersJS 3.1.7

**Comment by daffl** [comment]
It is not passed because it is not clear if this is a security relevant parameter. If you don't think it is for you application, it is a two-liner before hook to enable a `$collation` query parameter:

```js
context => {
  context.params.collation = params.query.$collation;
  return context;
}
```
