### ISSUE TITLE
Change _Id to id

### ISSUE THREAD

**Issue by giancarllorojas** [feathersjs-ecosystem/feathers-mongoose#325]
### Steps to reproduce

```javascript
  const options = {
    name: 'pipeline',
    Model,
    paginate,
    id: 'id'
  };

  // Initialize our service with any options it requires
  app.use('/pipeline', createService(options));
```

### Expected behavior
Service should use the _id property as "id" when querying and creating new elements.

### Actual behavior
But It doesn't work, the service keeps creating documents with "_id" property and having the id as "_id" when querying. Am I doing something wrong?

### System configuration

**Module versions**
"@feathersjs/feathers":  "version": "3.3.1"
"feathers-mongoose": "version": "7.3.2",
"mongoose": "version": "5.5.12"

**NodeJS version**:
v10.12.0

**Comment by daffl** [comment]
An `_id` property will always be generated by MongoDB. When changing the property the adapter will use that `id` field for `get` and other queries however. Keep in mind that custom id field values will not be generated automatically.

**Comment by giancarllorojas** [comment]
Oh, I got with, I thought that the "id" was for specifying the "_id" alias.

Thanks for the answer @daffl. 

Do you have any idea of how I should do It then? I just need an alias for the _id property because I'm migrating my project from feathers-knex to feathers-mongoose and my frontend already uses the property "id". I've tried putting a Mongoose alias in the schema, but It didn't work either.

**Comment by matiaslopezd** [comment]
@daffl I tried to use this two libraries but without result. This issue I have is related to this other [issue](https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/202)?

LIbraries to change _id to id on the response (not on DB): 
- https://github.com/meanie/mongoose-to-json
- https://github.com/abranhe/normalize-mongoose
