### ISSUE TITLE
`whitelist` property should merge with mongoose defaults

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-mongoose#347]
I believe the `whitelist` option in the service constructor should be merged with the mongoose specific operators that are hard coded in the service, rather than overwrite them totally.
see: https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/df73ef0ad1f8b1d551d9d958de12f909c23967fc/lib/service.js#L16

When adding a whitelist such as `['$exists']`, the default `['$and', '$regex']` is overwritten rather than returning `['$and', '$regex', `$exists`]`.

I believe this is how `feathers-sequelize` works as per: https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/a2e9d4fcee2e9010720d08ac52581f92b0e39e7a/lib/index.js#L40

This is only a mild annoyance. It is simple enough to look into the source code and be sure to include `['$and', '$regex']` (if you are using them). But I do think it would be nice to merge them as well as have similar behavior across the DB adapters (to be fair, I have only looked at how feathers-sequelize handles this).

One caveat to this would be that there is no way to remove an operator. For example, I could not remove `['$and', '$regex']`

I would be happy to open a PR for this if you guys think it is a good idea.

**Comment by DaddyWarbucks** [comment]
Related: https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/324

**Comment by daffl** [comment]
I updated it to always include $and since it is used by the adapter.
