### ISSUE TITLE
feathers service

### ISSUE THREAD

**Issue by subash891** [feathersjs-ecosystem/feathers-mongoose#352]
this is reset.class.js
const { Service } = require('feathers-sequelize');
const axios       = require('axios');
const app = require('../../app');

exports.ResetPassword = class ResetPassword extends Service {
  
    create(data){
      console.log(app);
      const users = app.service('users');
      //   var id = 1;
      //   return users.patch(id,data);
    }
    
    
};

here how to i use user service,

**Comment by daffl** [comment]
This is the Mongoose repository. How this all fits together is also described in [the Guide](https://docs.feathersjs.com/guides/), e.g. the [Quick start](https://docs.feathersjs.com/guides/basics/starting.html) chapter.
