### ISSUE TITLE
Can't get softDelete2 working properly!!

### ISSUE THREAD

**Issue by AGMHP** [feathersjs-ecosystem/feathers-mongoose#367]
//NodeJS version: 10.16.3
//"feathers-hooks-common": "^5.0.1",

//stats services for which I'm trying to implement softDelete2, so that it will flag all the documents as deleted after remove request

//stats class
const { softDelete2 } = require('feathers-hooks-common');

const optionsBefore = {
  deletedAt: -1,
  keepOnCreate: true,
  skipProbeOnGet: false,
  allowIgnoreDeletedAt: true
};

const optionsAfter = {
  deletedAt: 1,
  skipProbeOnGet: false,
  allowIgnoreDeletedAt: true
};

module.exports = {
  before: {
    all: [softDelete2(optionsBefore)],
    find: [],
    get: [],
    create: [softDelete2()],
    update: [],
    patch: [],
    remove: [softDelete2(optionsAfter)]
  },

  after: {
    all: [softDelete2(optionsBefore)],
    find: [context => {console.log(context.result);}],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

I'm keep running into an error of softDelete2 is not a function.

**Comment by daffl** [comment]
Use the [new softDelete](https://hooks-common.feathersjs.com/hooks.html#softdelete) with `feathers-hooks-common` version 5.0.0 or later.

**Comment by AGMHP** [comment]
**Thanks so much, softDelete is working now**..
is there any hooks so i can render or change the context.result.data, like sort all the data and then 
change the object's structure.

after the request the object's would look like this:
{
  _id: ObjectId,
  latest: Boolean,
  schema_version: Number,
  asset_type: String,
  asset_id: String,
  stat: String,
  value: Any,
  date: Date,
  created_at: Date,
  updated_at: Date,
}

then with the expected hook or query we can build an object like this:

[
  {
    _id: '<channel_id>',
    subscribers: [
      {value: Number, date: Date},
      // most recent 10 records
    ],
    posts_30d: [
      {value: Number, date: Date},
      // most recent 10 records
    ]
  },
]

help will be appreciated!!!

**Comment by arfanliaqat** [comment]
u can sort data before fetching with `$sort` query option. and for formatting i think u mean u want to join `subscribers` and `post_30d` data... i think you'd look into `fastJoin` hook

**Comment by daffl** [comment]
This might also work better with the [new softDelete](https://hooks-common.feathersjs.com/hooks.html#softdelete).
