### ISSUE TITLE
_get and _patch "No record found for id"

### ISSUE THREAD

**Issue by achilsowa** [feathersjs-ecosystem/feathers-mongoose#369]
Hi
First I apologize because I can't describe step to reproduce. 
This is part of the problem actually. Some time _get called on the service model find the element in the database and some other times it does not, even though the element is present

May be other users experienced the same issue. This is why I'm posting it there

I call them simply without any params most of the time

service._get(id)
service._patch(id, data)

Thanks

**Comment by arfanliaqat** [comment]
can u provide more information regarding ur setup? are u sure that correct id is passed to these methods. the id passed may be null due to some logic?
