### ISSUE TITLE
Support arrayFilter in patch

### ISSUE THREAD

**Issue by GaborTorma** [feathersjs-ecosystem/feathers-mongoose#373]
Please support array filtering in patch method.
https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/

**Comment by arfanliaqat** [comment]
I think u can already use it just set it as mongoose option

```
context.params.mongoose = {
    arrayFilters: [{ key: value }],
};
```

**Comment by GaborTorma** [comment]
Thanx! I found it, but it's hook.
Is it possible to define it on client side?

**Comment by arfanliaqat** [comment]
You can use a hack, recommended by maintainers for similar needs

```
// pass arrayFilters as normal query from client
app.service("comments").patch(_id, { query: { arrayFilters: [{ key: value }] } });


// on server side inside a before patch hook in comments service
context => {
    const { query, mongoose } = context.params;

    if (query.hasOwnProperty("arrayFilters")) {
        // merge existing mongoose options with array filters from client
        context.params.mongoose = { ...mongoose, arrayFilters: query.arrayFilters };
        
        // delete arrayFilters key from query because it is not supposed to be there
        delete context.params.query.arrayFilters;
    }

    return context;
}
```
You can use it for any other method i.e. create, get, find, or remove as well.

**Comment by GaborTorma** [comment]
Ohh, thanx! Good solution.
Last question: why not pass it from patch method third parameter (params)?
Like these: `patch(id, data, {
    mongoose: {
       arrayFilters: [ { key: value } ]
    }
})`

**Comment by arfanliaqat** [comment]
For security reasons maintainers decided not to allow passing all kinda params from client. A few things can only be done on server side. This is one of those cases. However i've seen the above pattern being recommended in several other discussions

**Comment by arfanliaqat** [comment]
https://docs.feathersjs.com/api/services.html#params here at the end of params section u can read an important note 

```
Important: For external calls only params.query will be sent 
between the client and server. If not passed, params.query 
will be undefined for internal calls.
```

So its by design... but u can bypass as per ur need with above pattern

**Comment by daffl** [comment]
Looks like this is solved. Thanks @arfanliaqat!
