### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by waltergammarota** [feathersjs-ecosystem/feathers-mongoose#375]
I need to run a query on the DB, using aggregation. I mean $sum, $group, $etc.
Is this possible, I can't figure out a way to do it.
Can anybody help me?

**Comment by jamesjnadeau** [comment]
Please try searching closed issues before asking questions.

I did a search on aggregation and found this pretty quickly, it describes how to solve your issue.
https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/212
