### ISSUE TITLE
bug in custom route hooks ( authentication )

### ISSUE THREAD

**Issue by webafra** [feathersjs-ecosystem/feathers-mongoose#381]
hi .

I want to create a custom route and authenticate that path.
The following code is written to do this:

**=> users.service.js**

```
const { authenticate } = require('@feathersjs/authentication').hooks;

app.use('/users/me/ads', {
    async find (context) {
      const { user } = context;
      console.log('user is:', user);
      context.query.user = user._id;
      return await service._find(context);
    },
  }).hooks({
    before: {
      find: [
        authenticate('jwt')
      ]
    }
  })

```

But after writing this code, all other ( '/pages' , '/ads' and ... ) routes need authentication!
after remove this `authenticate('jwt')` on find hook, no problem to other routes ( '/pages', '/ads' ... ) .

what is my problem ? 

feathers version: 4.5.3
node js : 13

**Comment by daffl** [comment]
`app.use` returns the `app` object, not the service, so you are initializing an [application level hook](https://docs.feathersjs.com/api/hooks.html#application-hooks) not a service hooks. Service hooks are [initialized like this](https://docs.feathersjs.com/api/hooks.html#registering-hooks):

```js
const { authenticate } = require('@feathersjs/authentication').hooks;

app.use('/users/me/ads', {
  async find (context) {
    const { user } = context;
    console.log('user is:', user);
    context.query.user = user._id;
    return await service._find(context);
  },
});

app.service('/users/me/ads').hooks({
  before: {
    find: [
      authenticate('jwt')
    ]
  }
});
```
