### ISSUE TITLE
Crear vistas en feathers-mongoose

### ISSUE THREAD

**Issue by noelyriosquantion** [feathersjs-ecosystem/feathers-mongoose#392]
### Expected behavior
Hola, quería saber como puedo crear una vista de bbdd  con feathers-mongoose. Mi situación es la siguiente: Necesito crear una vista con 2 colecciones y luego hacer el filtrado de sobre dicha vista.

he probado hacer  mongoose.connection.createCollection('loads_views', {viewOn: 'loads', pipeline: []}) en un servicio y me crea la vista en la base de datos, pero quiero saber si esto lo puedo hacer desde feather-mongose con un propio schema, para evitar hacer el find de mongoose y utilizar el del hook de feathers.

**Comment by daffl** [comment]
Please submit your issues in English ([translators have gotten pretty good](https://translate.google.com/)), we unfortunately have no Spanish speakers here.
