### ISSUE TITLE
Compatibility issues with mongoose < 5.2.0

### ISSUE THREAD

**Issue by Solant** [feathersjs-ecosystem/feathers-mongoose#393]
### Steps to reproduce

Compatibility issues with mongoose < 5.2.0

Due to the usage of Query.session() method, this library is not compatible with mongoose version prior to transaction support (5.2.0)

for example here: https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/5fbe56007b8576d350cb78d4a4a4312e7ad54eb1/lib/service.js#L144

### Expected behavior
Version compatibility message in repo README file or handling of mongoose versions without transactions

### Actual behavior
Error `modelQuery.session` is not a function

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This module is only intended to work with the latest version. You can also try installing [version 7.0 or prior](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/CHANGELOG.md).
