### ISSUE TITLE
Sort outer collection by populated inner collections

### ISSUE THREAD

**Issue by f-i-t-s-u-m** [feathersjs-ecosystem/feathers-mongoose#399]
I search the whole week for this.
i want to sort parent collection from inner child populated collection 

this result is without any filter sort  query :

http://localhost:3030/user-institutions?$populate=user

``` 
{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},

]}

```

so i try to filter using feathers mongoose query 
http://localhost:3030/user-institutions?$populate=user&$sort[user.name]=1

i was expected to get

```

{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},


] 

```
but I cant get any different result from the first results.  am still getting the first result which is not in alphabetic ascending. 
still getting this result 
``` 
{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},

]} 
```

if you have any solution for this on feathers mongoose adapter please let me know as soon as possible 

thanks for your time

**Comment by J3m5** [comment]
This might be because the sort operation is applied before the populate one.
You should try to re-implement the find method of the adapter service class by applying the populate before the sort.

If you look at the mongoose docs on populate, sort is always applied after populate.

**Comment by f-i-t-s-u-m** [comment]
> This might be because the sort operation is applied before the populate one.
> You should try to re-implement the find method of the adapter service class by applying the populate before the sort.
> 
> If you look at the mongoose docs on populate, sort is always applied after populate.

Am using mongoose adapter for feathersjs. i think  sort is applied after populate as  you said

**Comment by J3m5** [comment]
I was talking about feathers-mongoose, [here is the line where the sort is applied ](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/1f39950d427694088490f421ffe1dc756b9994e7/lib/service.js#L68).

And populate is applied [on line 88](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/1f39950d427694088490f421ffe1dc756b9994e7/lib/service.js#L88).

**Comment by f-i-t-s-u-m** [comment]
@J3m5  i want to say thank you for your time i found the solution for my problem if anyone walking have the same problem. let me show you my problem 

i was trying to sort by http://localhost:3030/user-institutions?$populate=user&$sort[user.name]=1

which is not correct.
 just what i have to do was 

http://localhost:3030/user-institutions?$populate=user&$sort[user]=1
the above method is correct 

you can use SELECT query method if you have got in trouble

**Comment by f-i-t-s-u-m** [comment]
> And if you look at [the mongoose docs](https://mongoosejs.com/docs/populate.html#), sort is always applied after populate, this might be why it doesn't works.
> But this is just a guess.


I was playing in mongodb doc console after you proved me with the above link.
i just figure out playing 
thank you for hint
