### ISSUE TITLE
`upsert: true` skips schema validation 

### ISSUE THREAD

**Issue by antarasi** [feathersjs-ecosystem/feathers-mongoose#403]
### Steps to reproduce

model definition
```
const schema = new Schema({
    name: { type: String, required: true, index: true },
    timestamp: { type: Date, required: true, index: true },
});
```

service call
```
await this.service('/servicename').patch(null, {
            datapoint: 'something else',
          }, {
            query: {
              timestamp,
            },
            mongoose: {
              upsert: true
            }
          });
```

returns
```
{
    _id: 6076d827b062512dc8baa600,
    timestamp: 2021-04-14T11:55:19.425Z,
    __v: 0,
    createdAt: 2021-04-14T11:55:19.705Z,
    updatedAt: 2021-04-14T11:55:19.705Z
}
```

calling create method directly with the same data returns (as expected)
```
BadRequest: validation failed: name: Path `name` is required.
```

### Expected behavior
Should throw `name` is missing.

### Actual behavior
Schema is not validated leaving `name` undefined.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
    "@feathersjs/configuration": "^4.5.9",
    "@feathersjs/errors": "^4.5.9",
    "@feathersjs/feathers": "^4.5.9",
    "@feathersjs/socketio": "^4.5.9",
    "feathers-mongoose": "^8.3.1",
```

**NodeJS version**:
`v12.18.3`

**Operating System**:
n/a

**Browser Version**:
n/a

**React Native Version**:
n/a

**Module Loader**:
n/a

**Comment by bwgjoseph** [comment]
It's actually not related to `feathers-mongoose` but `mongoose`. Take a look at [here](https://github.com/Automattic/mongoose/issues/9494)

**Comment by antarasi** [comment]
Thanks. Calling `Model.validate()` solves the problem there.
