### ISSUE TITLE
`upsert: true` does not support `multi: 'patch'`

### ISSUE THREAD

**Issue by antarasi** [feathersjs-ecosystem/feathers-mongoose#404]
### Steps to reproduce

model definition
```
const schema = new Schema({
    name: { type: String, required: true, index: true },
    timestamp: { type: Date, required: true, index: true },
});
```

service definition
```
const options = {
    Model: createModel(app),
    multi: ['create', 'patch'],
  };
```

service call
```
await this.service('/servicename').patch(null, [{
            name: 'some name',
          }], {
            query: {
              timestamp: new Date(),
            },
            mongoose: {
              upsert: true
            }
          });
```

returns (`name` missing)
```
{
    _id: 6076d827b062512dc8baa600,
    timestamp: 2021-04-14T11:55:19.425Z,
    __v: 0,
    createdAt: 2021-04-14T11:55:19.705Z,
    updatedAt: 2021-04-14T11:55:19.705Z
}
```

calling create method directly
```
await this.service('/metrics').create([{
            name: 'some name',
            timestamp: new Date(),
          }]);
```

returns (as expected)
```
{
    _id: 6076ddeb1ceff8286100102b,
    name: 'some name',
    timestamp: 2021-04-14T12:19:55.660Z,
    createdAt: 2021-04-14T12:19:55.890Z,
    updatedAt: 2021-04-14T12:19:55.890Z,
    __v: 0
  }
```

### Expected behavior
multi-patch service call should create `name` field.

### Actual behavior
Data passed as array is discarded, only `params.query` arguments are passed to the db document.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
    "@feathersjs/configuration": "^4.5.9",
    "@feathersjs/errors": "^4.5.9",
    "@feathersjs/feathers": "^4.5.9",
    "@feathersjs/socketio": "^4.5.9",
    "feathers-mongoose": "^8.3.1",
```

**NodeJS version**:
`v12.18.3`

**Operating System**:
n/a

**Browser Version**:
n/a

**React Native Version**:
n/a

**Module Loader**:
n/a

**Comment by bwgjoseph** [comment]
See #403. Anyway, the syntax is a bit off.

```js
// note no []
await this.service('/servicename').patch(null, {
            name: 'some name',
          }, {
            query: {
              timestamp: new Date(),
            },
            mongoose: {
              upsert: true
            }
          });
```

Also, your query will never match any doc as well since you pass in new date

**Comment by antarasi** [comment]
> Also, your query will never match any doc as well since you pass in new date

Yes, that's just for an example purposes - I want to see what documents are created with upsert when there's no match to query.

Why do you think the syntax is off? 
As per the issue title I supposed the upsert should work for `multi: true` - with `patch(null, [{...}])`

**Comment by bwgjoseph** [comment]
The API remains the same even with `multi` enabled

```js
// https://docs.feathersjs.com/api/databases/common.html#adapter-patch-id-data-params
patch(id, data, params)
```

https://github.com/feathersjs/feathers/blob/501d4164d30c6a126906dc640cdfdc82207ba34a/packages/adapter-commons/src/service.ts#L196

**Comment by antarasi** [comment]
Okay, so why you say the syntax is off?

in the call:
```
patch(null, [{
            name: 'some name',
          }], {
            query: {
              timestamp: new Date(),
            },
            mongoose: {
              upsert: true
            }
          });
```

```
id = null
```

```
data = [{
            name: 'some name',
          }] // array of items - should be supported by adding `multi: 'patch'` to the service definition
```

```
params = {
            query: {
              timestamp: new Date(),
            },
            mongoose: {
              upsert: true
            }
          }
```

**Comment by bwgjoseph** [comment]
As far as I understand, the `data` should be an `object` and not a `array of objects` when updating/patching even with `multi` on

So it should be something like

```js
patch(null, { name: 'some name' }, { query: { isActive: true } })
```

It is updating all documents that matches the query where `isActive is equal to true` and setting the `name` field to `some name`

**Comment by antarasi** [comment]
Got it, thanks.
